ThhEnum = {
  AddonMessageType = {
    Heartbeat = 0,
    PlayerDisconnected = 1,
    EnteredCombat = 11,
    ExitedCombat = 12,
    LoggingOut = 13,
    LogoutCancelled = 14,
    HealthLow = 15,
    HealthCriticallyLow = 16,
    SpellCastStarted = 17,
    SpellCastInterrupted = 18,
  },
  NotificationType = {
    PlayerDisconnected = 1,
    PlayerReconnected = 2,
    EnteredCombat = 11,
    LoggingOut = 13,
    LogoutCancelled = 14,
    HealthLow = 15,
    HealthCriticallyLow = 16,
    SpellCastStarted = 17,
    SpellCastInterrupted = 18,
    AuraApplied = 20,
  },
}